[phases.setup]
nixPkgs = ["python3", "gcc", "postgresql_16.dev"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip --no-cache-dir",
  ". /opt/venv/bin/activate && pip install --no-cache-dir --no-warn-script-location -r requirements.txt"
]

[start]
cmd = "python src/bot.py"

